In [1]:
using DataFrames

In [2]:
arr(1, 2, 3, 4, 5, 6, 7, 8)

LoadError: LoadError: UndefVarError: arr not defined
while loading In[2], in expression starting on line 1

In [3]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]

8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8

In [4]:
da1 = DataArray(arr)

8-element DataArrays.DataArray{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8

In [5]:
da2 = @data([1, 3, 5, 7, 9])

5-element DataArrays.DataArray{Int64,1}:
 1
 3
 5
 7
 9

In [6]:
mapreduce(x -> x^2, +, da2)

165

In [7]:
sum(map(x -> x^2, da2))

165

In [8]:
reduce(+, da1)

36

In [9]:
df1 = DataFrame(A = 1:5, B = ["Y", "Y", "N", "Y", "N"])

5×2 DataFrames.DataFrame
│ Row │ A │ B   │
├─────┼───┼─────┤
│ 1   │ 1 │ "Y" │
│ 2   │ 2 │ "Y" │
│ 3   │ 3 │ "N" │
│ 4   │ 4 │ "Y" │
│ 5   │ 5 │ "N" │

In [10]:
df2 = DataFrame()

0×0 DataFrames.DataFrame

In [11]:
df2[:A] = 1:5
df2[:B] = ["This", "Is", "a", "new", "column"]

5-element Array{ASCIIString,1}:
 "This"  
 "Is"    
 "a"     
 "new"   
 "column"

In [12]:
df2

5×2 DataFrames.DataFrame
│ Row │ A │ B        │
├─────┼───┼──────────┤
│ 1   │ 1 │ "This"   │
│ 2   │ 2 │ "Is"     │
│ 3   │ 3 │ "a"      │
│ 4   │ 4 │ "new"    │
│ 5   │ 5 │ "column" │

In [13]:
size(df2)

(5,2)

In [14]:
typeof(size(df2))

Tuple{Int64,Int64}

In [15]:
no_of_rows = size(df2, 1)

5

In [16]:
no_of_cols = size(df2, 2)

2

In [17]:
df3 = DataFrame()

0×0 DataFrames.DataFrame

In [18]:
rand(3)

3-element Array{Float64,1}:
 0.138644
 0.888   
 0.954514

In [35]:
df3[:A] = rand(15)
df3[:B] = rand(15)
df3[:C] = rand(15)
df3[:D] = rand(15)

LoadError: LoadError: indexing Array{Symbol,1} with types Tuple{Symbol} is not supported
while loading In[35], in expression starting on line 1

In [20]:
df3

15×4 DataFrames.DataFrame
│ Row │ A         │ B        │ C         │ D         │
├─────┼───────────┼──────────┼───────────┼───────────┤
│ 1   │ 0.653871  │ 0.467659 │ 0.445691  │ 0.549726  │
│ 2   │ 0.256817  │ 0.920834 │ 0.257119  │ 0.13207   │
│ 3   │ 0.626193  │ 0.76451  │ 0.720053  │ 0.632804  │
│ 4   │ 0.0876497 │ 0.996206 │ 0.747403  │ 0.652716  │
│ 5   │ 0.212283  │ 0.997907 │ 0.0557518 │ 0.522682  │
│ 6   │ 0.96981   │ 0.332475 │ 0.868762  │ 0.127411  │
│ 7   │ 0.642994  │ 0.098241 │ 0.889169  │ 0.781938  │
│ 8   │ 0.274004  │ 0.107347 │ 0.234137  │ 0.0653536 │
│ 9   │ 0.687211  │ 0.729339 │ 0.360262  │ 0.363306  │
│ 10  │ 0.980399  │ 0.340387 │ 0.994256  │ 0.590866  │
│ 11  │ 0.450372  │ 0.652829 │ 0.573301  │ 0.517595  │
│ 12  │ 0.266111  │ 0.736413 │ 0.0959708 │ 0.993473  │
│ 13  │ 0.672536  │ 0.946478 │ 0.546903  │ 0.774954  │
│ 14  │ 0.946084  │ 0.651717 │ 0.960952  │ 0.0397436 │
│ 15  │ 0.414663  │ 0.92682  │ 0.0851566 │ 0.669988  │

In [21]:
head(df3)

6×4 DataFrames.DataFrame
│ Row │ A         │ B        │ C         │ D        │
├─────┼───────────┼──────────┼───────────┼──────────┤
│ 1   │ 0.653871  │ 0.467659 │ 0.445691  │ 0.549726 │
│ 2   │ 0.256817  │ 0.920834 │ 0.257119  │ 0.13207  │
│ 3   │ 0.626193  │ 0.76451  │ 0.720053  │ 0.632804 │
│ 4   │ 0.0876497 │ 0.996206 │ 0.747403  │ 0.652716 │
│ 5   │ 0.212283  │ 0.997907 │ 0.0557518 │ 0.522682 │
│ 6   │ 0.96981   │ 0.332475 │ 0.868762  │ 0.127411 │

In [22]:
tail(df3, 3)

3×4 DataFrames.DataFrame
│ Row │ A        │ B        │ C         │ D         │
├─────┼──────────┼──────────┼───────────┼───────────┤
│ 1   │ 0.672536 │ 0.946478 │ 0.546903  │ 0.774954  │
│ 2   │ 0.946084 │ 0.651717 │ 0.960952  │ 0.0397436 │
│ 3   │ 0.414663 │ 0.92682  │ 0.0851566 │ 0.669988  │

In [23]:
showcols(df3)

15×4 DataFrames.DataFrame
│ Col # │ Name │ Eltype  │ Missing │
├───────┼──────┼─────────┼─────────┤
│ 1     │ A    │ Float64 │ 0       │
│ 2     │ B    │ Float64 │ 0       │
│ 3     │ C    │ Float64 │ 0       │
│ 4     │ D    │ Float64 │ 0       │

In [24]:
eltypes(df3)

4-element Array{Type{T},1}:
 Float64
 Float64
 Float64
 Float64

In [25]:
dump(df30)

LoadError: LoadError: UndefVarError: df30 not defined
while loading In[25], in expression starting on line 1

In [26]:
dump(df3)

DataFrames.DataFrame  15 observations of 4 variables
  A: DataArrays.DataArray{Float64,1}(15) [0.6538712733206986,0.2568169311860924,0.6261925263039021,0.08764967641704247]
  B: DataArrays.DataArray{Float64,1}(15) [0.4676586280993684,0.9208340216599429,0.7645098074109309,0.9962056158630292]
  C: DataArrays.DataArray{Float64,1}(15) [0.44569058202006495,0.2571194180530427,0.7200529771510062,0.7474026686306194]
  D: DataArrays.DataArray{Float64,1}(15) [0.5497262353824863,0.13207046011145906,0.632804338135158,0.6527159812809706]


In [27]:
describe(df30)

LoadError: LoadError: UndefVarError: df30 not defined
while loading In[27], in expression starting on line 1

In [28]:
describe(df3)

A
Min      0.08764967641704247
1st Qu.  0.27005730160457553
Median   0.6261925263039021
Mean     0.5427330229953619
3rd Qu.  0.6798730928300392
Max      0.9803988600560456
NAs      0
NA%      0.0%

B
Min      0.09824104619985352
1st Qu.  0.4040230599803514
Median   0.7293386144210177
Mean     0.6446107310398463
3rd Qu.  0.9238271101483746
Max      0.9979068435170713
NAs      0
NA%      0.0%

C
Min      0.05575177217708882
1st Qu.  0.24562810640213273
Median   0.5469033424500562
Mean     0.5223258212907417
3rd Qu.  0.8080825293920816
Max      0.9942561780555055
NAs      0
NA%      0.0%

D
Min      0.03974364570675304
1st Qu.  0.24768842669184743
Median   0.5497262353824863
Mean     0.4943085112919344
3rd Qu.  0.6613518916578736
Max      0.9934728950484661
NAs      0
NA%      0.0%



In [29]:
describe(df2)

A
Min      1.0
1st Qu.  2.0
Median   3.0
Mean     3.0
3rd Qu.  4.0
Max      5.0
NAs      0
NA%      0.0%

B
Length  5
Type    ASCIIString
NAs     0
NA%     0.0%
Unique  5



In [30]:
df3[:A]

15-element DataArrays.DataArray{Float64,1}:
 0.653871 
 0.256817 
 0.626193 
 0.0876497
 0.212283 
 0.96981  
 0.642994 
 0.274004 
 0.687211 
 0.980399 
 0.450372 
 0.266111 
 0.672536 
 0.946084 
 0.414663 

In [37]:
df3[3:5, 1]

LoadError: LoadError: BoundsError: attempt to access 2-element Array{Symbol,1}:
 :A
 :C
  at index [3:5,1]
while loading In[37], in expression starting on line 1

In [36]:
df3[3:5, :]

LoadError: LoadError: BoundsError: attempt to access 2-element Array{Symbol,1}:
 :A
 :C
  at index [3:5,Colon()]
while loading In[36], in expression starting on line 1

In [38]:
;ls

CCS.csv
Data Frames practice.ipynb
GadflyTutorialData.csv
Week4_1Collections.ipynb
Week4_2Functions.ipynb
Week4_3DataFrames.ipynb
Week4_4Data.ipynb
Week4_Honors2-Gadfly.ipynb
functions recap.ipynb
style.css


In [39]:
data1 = readtable("CCS.csv")

120×6 DataFrames.DataFrame
│ Row │ PatientID │ Cat1 │ Cat2 │ Var1    │ Var2    │ Var3    │
├─────┼───────────┼──────┼──────┼─────────┼─────────┼─────────┤
│ 1   │ 1         │ "A"  │ "C"  │ 38.2568 │ 5.93913 │ 35.0579 │
│ 2   │ 2         │ "A"  │ "C"  │ 17.8317 │ 5.34754 │ 21.131  │
│ 3   │ 8         │ "A"  │ "B"  │ 16.0218 │ 6.60709 │ 60.9436 │
│ 4   │ 9         │ "A"  │ "C"  │ 45.1158 │ 6.00733 │ 21.8797 │
│ 5   │ 16        │ "A"  │ "C"  │ 20.448  │ 8.54819 │ 20.6623 │
│ 6   │ 18        │ "A"  │ "B"  │ 28.3549 │ 7.95642 │ 33.1807 │
│ 7   │ 25        │ "A"  │ "C"  │ 22.4497 │ 6.34618 │ 40.2365 │
│ 8   │ 28        │ "A"  │ "B"  │ 48.4125 │ 5.32583 │ 28.8956 │
│ 9   │ 29        │ "A"  │ "C"  │ 40.0075 │ 11.4189 │ 71.5911 │
│ 10  │ 33        │ "A"  │ "C"  │ 20.7181 │ 5.37768 │ 27.4216 │
│ 11  │ 37        │ "A"  │ "B"  │ 17.0396 │ 5.34168 │ 24.3501 │
⋮
│ 109 │ 76        │ "B"  │ "R"  │ 17.0029 │ 5.39477 │ 31.1297 │
│ 110 │ 78        │ "B"  │ "L"  │ 55.3879 │ 4.15304 │ 40.0846 │
│ 111 │ 80        │ "B"  │ "R"  │ 20.2205 │ 6.36442 │ 45.435  │
│ 112 │ 83        │ "B"  │ "L"  │ 16.4172 │ 3.84167 │ 89.6969 │
│ 113 │ 84        │ "B"  │ "R"  │ 47.6224 │ 5.40032 │ 47.4541 │
│ 114 │ 86        │ "B"  │ "L"  │ 73.0229 │ 3.38349 │ 55.1737 │
│ 115 │ 92        │ "B"  │ "R"  │ 16.4106 │ 4.30351 │ 87.7357 │
│ 116 │ 95        │ "B"  │ "R"  │ 16.2801 │ 3.37252 │ 52.6018 │
│ 117 │ 101       │ "B"  │ "L"  │ 16.8883 │ 3.19598 │ 60.1883 │
│ 118 │ 113       │ "B"  │ "R"  │ 32.3537 │ 3.38677 │ 30.0157 │
│ 119 │ 115       │ "B"  │ "R"  │ 20.1379 │ 3.42731 │ 44.6893 │
│ 120 │ 119       │ "B"  │ "L"  │ 17.6144 │ 3.45116 │ 40.6947 │

In [40]:
describe(data1)

PatientID
Min      1.0
1st Qu.  30.75
Median   60.5
Mean     60.5
3rd Qu.  90.25
Max      120.0
NAs      0
NA%      0.0%

Cat1
Length  120
Type    UTF8String
NAs     0
NA%     0.0%
Unique  2

Cat2
Length  120
Type    UTF8String
NAs     0
NA%     0.0%
Unique  6

Var1
Min      15.235601323477356
1st Qu.  17.967474764822036
Median   22.68007894647561
Mean     27.967863792237896
3rd Qu.  34.74637250355623
Max      84.23781038235661
NAs      0
NA%      0.0%

Var2
Min      3.0117329341084575
1st Qu.  4.065522629370978
Median   5.642405804079912
Mean     5.921205494236093
3rd Qu.  6.839650568847201
Max      15.58264883701855
NAs      0
NA%      0.0%

Var3
Min      20.315296150337286
1st Qu.  32.235513889318256
Median   44.30417639037034
Mean     51.95003059213374
3rd Qu.  64.8588498831561
Max      147.39740194224694
NAs      0
NA%      0.0%



In [41]:
head(data1)

6×6 DataFrames.DataFrame
│ Row │ PatientID │ Cat1 │ Cat2 │ Var1    │ Var2    │ Var3    │
├─────┼───────────┼──────┼──────┼─────────┼─────────┼─────────┤
│ 1   │ 1         │ "A"  │ "C"  │ 38.2568 │ 5.93913 │ 35.0579 │
│ 2   │ 2         │ "A"  │ "C"  │ 17.8317 │ 5.34754 │ 21.131  │
│ 3   │ 8         │ "A"  │ "B"  │ 16.0218 │ 6.60709 │ 60.9436 │
│ 4   │ 9         │ "A"  │ "C"  │ 45.1158 │ 6.00733 │ 21.8797 │
│ 5   │ 16        │ "A"  │ "C"  │ 20.448  │ 8.54819 │ 20.6623 │
│ 6   │ 18        │ "A"  │ "B"  │ 28.3549 │ 7.95642 │ 33.1807 │

In [42]:
typeof(data1)

DataFrames.DataFrame

In [46]:
?writetable

search: writetable



Write data to a tabular-file format (CSV, TSV, ...)

```julia
writetable(filename, df, [keyword options])
```

### Arguments

  * `filename::AbstractString` : the filename to be created
  * `df::AbstractDataFrame` : the AbstractDataFrame to be written

### Keyword Arguments

  * `separator::Char` – The separator character that you would like to use. Defaults to the output of `getseparator(filename)`, which uses commas for files that end in `.csv`, tabs for files that end in `.tsv` and a single space for files that end in `.wsv`.
  * `quotemark::Char` – The character used to delimit string fields. Defaults to `'"'`.
  * `header::Bool` – Should the file contain a header that specifies the column names from `df`. Defaults to `true`.
  * `nastring::AbstractString` – What to write in place of missing data. Defaults to `"NA"`.

### Result

  * `::DataFrame`

### Examples

```julia
df = DataFrame(A = 1:10)
writetable("output.csv", df)
writetable("output.dat", df, separator = ',', header = false)
writetable("output.dat", df, quotemark = '', separator = ',')
writetable("output.dat", df, header = false)
```


In [47]:
writetable("data1.csv", data1, separator = ',')

In [50]:
subjects = DataFrame(Number = [100, 101, 102, 103], Stage = ["I", "II", "III", "I"])

4×2 DataFrames.DataFrame
│ Row │ Number │ Stage │
├─────┼────────┼───────┤
│ 1   │ 100    │ "I"   │
│ 2   │ 101    │ "II"  │
│ 3   │ 102    │ "III" │
│ 4   │ 103    │ "I"   │

In [49]:
treatment = DataFrame(Number = [103, 102, 101, 100], Treatment = ["A", "B", "A", "B"])

4×2 DataFrames.DataFrame
│ Row │ Number │ Treatment │
├─────┼────────┼───────────┤
│ 1   │ 103    │ "A"       │
│ 2   │ 102    │ "B"       │
│ 3   │ 101    │ "A"       │
│ 4   │ 100    │ "B"       │

In [51]:
df5 = join(subjects, treatment, on = :Number)

4×3 DataFrames.DataFrame
│ Row │ Number │ Stage │ Treatment │
├─────┼────────┼───────┼───────────┤
│ 1   │ 100    │ "I"   │ "B"       │
│ 2   │ 101    │ "II"  │ "A"       │
│ 3   │ 102    │ "III" │ "B"       │
│ 4   │ 103    │ "I"   │ "A"       │

In [52]:
subjects = DataFrame(Number = [100, 101, 102, 103, 104, 105], Stage = ["I","III", "II", "I", "II", "II"])

6×2 DataFrames.DataFrame
│ Row │ Number │ Stage │
├─────┼────────┼───────┤
│ 1   │ 100    │ "I"   │
│ 2   │ 101    │ "III" │
│ 3   │ 102    │ "II"  │
│ 4   │ 103    │ "I"   │
│ 5   │ 104    │ "II"  │
│ 6   │ 105    │ "II"  │

In [53]:
df6 = join(subjects, treatment, on = :Number, kind = :inner)

4×3 DataFrames.DataFrame
│ Row │ Number │ Stage │ Treatment │
├─────┼────────┼───────┼───────────┤
│ 1   │ 100    │ "I"   │ "B"       │
│ 2   │ 101    │ "III" │ "A"       │
│ 3   │ 102    │ "II"  │ "B"       │
│ 4   │ 103    │ "I"   │ "A"       │

In [54]:
df7 = join(subjects, treatment, on = :Number, kind = :outer)

6×3 DataFrames.DataFrame
│ Row │ Number │ Stage │ Treatment │
├─────┼────────┼───────┼───────────┤
│ 1   │ 100    │ "I"   │ "B"       │
│ 2   │ 101    │ "III" │ "A"       │
│ 3   │ 102    │ "II"  │ "B"       │
│ 4   │ 103    │ "I"   │ "A"       │
│ 5   │ 104    │ "II"  │ NA        │
│ 6   │ 105    │ "II"  │ NA        │

In [55]:
df8 = DataFrame(Group = rand(["A", "B", "C"], 15),
variable1 = randn(15), variable2 = randn(15))

15×3 DataFrames.DataFrame
│ Row │ Group │ variable1 │ variable2  │
├─────┼───────┼───────────┼────────────┤
│ 1   │ "B"   │ -0.416821 │ -0.0698572 │
│ 2   │ "A"   │ 0.563161  │ -0.48732   │
│ 3   │ "A"   │ 1.4757    │ -0.722768  │
│ 4   │ "C"   │ 0.270719  │ -0.159861  │
│ 5   │ "C"   │ 0.726106  │ 0.892031   │
│ 6   │ "C"   │ 0.614097  │ 1.27636    │
│ 7   │ "B"   │ 1.22855   │ 1.32844    │
│ 8   │ "C"   │ 0.0289819 │ -0.346787  │
│ 9   │ "B"   │ -0.934414 │ -0.261611  │
│ 10  │ "A"   │ 0.350383  │ -0.172319  │
│ 11  │ "B"   │ 0.805701  │ -0.858425  │
│ 12  │ "B"   │ -2.20212  │ 0.62961    │
│ 13  │ "A"   │ 0.229074  │ 1.56088    │
│ 14  │ "B"   │ -0.649502 │ -0.302059  │
│ 15  │ "A"   │ 2.92004   │ -1.59193   │

In [56]:
by(df8, :Group, size)

3×2 DataFrames.DataFrame
│ Row │ Group │ x1    │
├─────┼───────┼───────┤
│ 1   │ "A"   │ (5,3) │
│ 2   │ "B"   │ (6,3) │
│ 3   │ "C"   │ (4,3) │

In [57]:
by(df8, :Group)

LoadError: LoadError: MethodError: `by` has no method matching by(::DataFrames.DataFrame, ::Symbol)
Closest candidates are:
  by(::DataFrames.AbstractDataFrame, ::Any, !Matched::Function)
  by(::DataFrames.AbstractDataFrame, ::Any, !Matched::Array{Symbol,1})
  by(::DataFrames.AbstractDataFrame, ::Any, !Matched::Symbol)
while loading In[57], in expression starting on line 1

In [58]:
by(df8, :Group, df -> DataFrame(Count = size(df, 1)))

3×2 DataFrames.DataFrame
│ Row │ Group │ Count │
├─────┼───────┼───────┤
│ 1   │ "A"   │ 5     │
│ 2   │ "B"   │ 6     │
│ 3   │ "C"   │ 4     │

In [59]:
aggregate(df8, :Group, [mean, std])

3×5 DataFrames.DataFrame
│ Row │ Group │ variable1_mean │ variable1_std │ variable2_mean │
├─────┼───────┼────────────────┼───────────────┼────────────────┤
│ 1   │ "A"   │ 1.10767        │ 1.12495       │ -0.282691      │
│ 2   │ "B"   │ -0.361434      │ 1.24038       │ 0.0776822      │
│ 3   │ "C"   │ 0.409976       │ 0.319454      │ 0.415436       │

│ Row │ variable2_std │
├─────┼───────────────┤
│ 1   │ 1.15765       │
│ 2   │ 0.777997      │
│ 3   │ 0.791683      │

In [60]:
groupby(df8, :Group)

DataFrames.GroupedDataFrame  3 groups with keys: [:Group]
First Group:
5×3 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ Group │ variable1 │ variable2 │
├─────┼───────┼───────────┼───────────┤
│ 1   │ "A"   │ 0.563161  │ -0.48732  │
│ 2   │ "A"   │ 1.4757    │ -0.722768 │
│ 3   │ "A"   │ 0.350383  │ -0.172319 │
│ 4   │ "A"   │ 0.229074  │ 1.56088   │
│ 5   │ "A"   │ 2.92004   │ -1.59193  │
⋮
Last Group:
4×3 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ Group │ variable1 │ variable2 │
├─────┼───────┼───────────┼───────────┤
│ 1   │ "C"   │ 0.270719  │ -0.159861 │
│ 2   │ "C"   │ 0.726106  │ 0.892031  │
│ 3   │ "C"   │ 0.614097  │ 1.27636   │
│ 4   │ "C"   │ 0.0289819 │ -0.346787 │

In [61]:
for i in groupby(df8, :Group)
    print(i)
end

5×3 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ Group │ variable1 │ variable2 │
├─────┼───────┼───────────┼───────────┤
│ 1   │ "A"   │ 0.563161  │ -0.48732  │
│ 2   │ "A"   │ 1.4757    │ -0.722768 │
│ 3   │ "A"   │ 0.350383  │ -0.172319 │
│ 4   │ "A"   │ 0.229074  │ 1.56088   │
│ 5   │ "A"   │ 2.92004   │ -1.59193  │6×3 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ Group │ variable1 │ variable2  │
├─────┼───────┼───────────┼────────────┤
│ 1   │ "B"   │ -0.416821 │ -0.0698572 │
│ 2   │ "B"   │ 1.22855   │ 1.32844    │
│ 3   │ "B"   │ -0.934414 │ -0.261611  │
│ 4   │ "B"   │ 0.805701  │ -0.858425  │
│ 5   │ "B"   │ -2.20212  │ 0.62961    │
│ 6   │ "B"   │ -0.649502 │ -0.302059  │4×3 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ Group │ variable1 │ variable2 │
├─────┼───────┼───────────┼───────────┤
│ 1   │ "C"   │ 0.270719  │ -0.159861 │
│ 2   │ "C"   │ 0.726106  │ 0.892031  │
│ 3   │ "C"   │ 0.614097  │ 1.27636   │
│ 4   │ "C"   │ 0.0289819 │ -0.346787 │

In [62]:
length(groupby(df8, :Group))

3

In [63]:
groupby(df8, :Group)[2]

6×3 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ Group │ variable1 │ variable2  │
├─────┼───────┼───────────┼────────────┤
│ 1   │ "B"   │ -0.416821 │ -0.0698572 │
│ 2   │ "B"   │ 1.22855   │ 1.32844    │
│ 3   │ "B"   │ -0.934414 │ -0.261611  │
│ 4   │ "B"   │ 0.805701  │ -0.858425  │
│ 5   │ "B"   │ -2.20212  │ 0.62961    │
│ 6   │ "B"   │ -0.649502 │ -0.302059  │

In [137]:
df8[:Variable3] = randn(15)

15-element Array{Float64,1}:
 -0.868551 
 -2.64537  
  0.467497 
  1.24686  
 -1.07683  
 -0.915358 
 -0.245615 
  0.206941 
 -0.548142 
 -1.33173  
 -0.0217244
 -1.62717  
  1.39622  
  0.198011 
  0.21189  

In [65]:
sub(df8, 5:7)

3×4 DataFrames.SubDataFrame{UnitRange{Int64}}
│ Row │ Group │ variable1 │ variable2 │ Variable3 │
├─────┼───────┼───────────┼───────────┼───────────┤
│ 1   │ "C"   │ 0.726106  │ 0.892031  │ -0.36738  │
│ 2   │ "C"   │ 0.614097  │ 1.27636   │ -1.19903  │
│ 3   │ "B"   │ 1.22855   │ 1.32844   │ 0.579553  │

In [67]:
sub(df8, df8[:variable1] .>= 0.5)

7×4 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ Group │ variable1 │ variable2 │ Variable3 │
├─────┼───────┼───────────┼───────────┼───────────┤
│ 1   │ "A"   │ 0.563161  │ -0.48732  │ -2.09803  │
│ 2   │ "A"   │ 1.4757    │ -0.722768 │ -0.555648 │
│ 3   │ "C"   │ 0.726106  │ 0.892031  │ -0.36738  │
│ 4   │ "C"   │ 0.614097  │ 1.27636   │ -1.19903  │
│ 5   │ "B"   │ 1.22855   │ 1.32844   │ 0.579553  │
│ 6   │ "B"   │ 0.805701  │ -0.858425 │ -0.283685 │
│ 7   │ "A"   │ 2.92004   │ -1.59193  │ 2.18142   │

In [68]:
df8A = sub(df8, df8[:Group] .== "A")

5×4 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ Group │ variable1 │ variable2 │ Variable3 │
├─────┼───────┼───────────┼───────────┼───────────┤
│ 1   │ "A"   │ 0.563161  │ -0.48732  │ -2.09803  │
│ 2   │ "A"   │ 1.4757    │ -0.722768 │ -0.555648 │
│ 3   │ "A"   │ 0.350383  │ -0.172319 │ 1.02911   │
│ 4   │ "A"   │ 0.229074  │ 1.56088   │ 1.24288   │
│ 5   │ "A"   │ 2.92004   │ -1.59193  │ 2.18142   │

In [69]:
sort!(df8)

15×4 DataFrames.DataFrame
│ Row │ Group │ variable1 │ variable2  │ Variable3 │
├─────┼───────┼───────────┼────────────┼───────────┤
│ 1   │ "A"   │ 0.229074  │ 1.56088    │ 1.24288   │
│ 2   │ "A"   │ 0.350383  │ -0.172319  │ 1.02911   │
│ 3   │ "A"   │ 0.563161  │ -0.48732   │ -2.09803  │
│ 4   │ "A"   │ 1.4757    │ -0.722768  │ -0.555648 │
│ 5   │ "A"   │ 2.92004   │ -1.59193   │ 2.18142   │
│ 6   │ "B"   │ -2.20212  │ 0.62961    │ -1.15986  │
│ 7   │ "B"   │ -0.934414 │ -0.261611  │ 0.307004  │
│ 8   │ "B"   │ -0.649502 │ -0.302059  │ 0.628162  │
│ 9   │ "B"   │ -0.416821 │ -0.0698572 │ -0.373174 │
│ 10  │ "B"   │ 0.805701  │ -0.858425  │ -0.283685 │
│ 11  │ "B"   │ 1.22855   │ 1.32844    │ 0.579553  │
│ 12  │ "C"   │ 0.0289819 │ -0.346787  │ 1.71514   │
│ 13  │ "C"   │ 0.270719  │ -0.159861  │ 1.47013   │
│ 14  │ "C"   │ 0.614097  │ 1.27636    │ -1.19903  │
│ 15  │ "C"   │ 0.726106  │ 0.892031   │ -0.36738  │

In [70]:
sort!(df8, cols = [:Group, :variable1], rev = true)

15×4 DataFrames.DataFrame
│ Row │ Group │ variable1 │ variable2  │ Variable3 │
├─────┼───────┼───────────┼────────────┼───────────┤
│ 1   │ "C"   │ 0.726106  │ 0.892031   │ -0.36738  │
│ 2   │ "C"   │ 0.614097  │ 1.27636    │ -1.19903  │
│ 3   │ "C"   │ 0.270719  │ -0.159861  │ 1.47013   │
│ 4   │ "C"   │ 0.0289819 │ -0.346787  │ 1.71514   │
│ 5   │ "B"   │ 1.22855   │ 1.32844    │ 0.579553  │
│ 6   │ "B"   │ 0.805701  │ -0.858425  │ -0.283685 │
│ 7   │ "B"   │ -0.416821 │ -0.0698572 │ -0.373174 │
│ 8   │ "B"   │ -0.649502 │ -0.302059  │ 0.628162  │
│ 9   │ "B"   │ -0.934414 │ -0.261611  │ 0.307004  │
│ 10  │ "B"   │ -2.20212  │ 0.62961    │ -1.15986  │
│ 11  │ "A"   │ 2.92004   │ -1.59193   │ 2.18142   │
│ 12  │ "A"   │ 1.4757    │ -0.722768  │ -0.555648 │
│ 13  │ "A"   │ 0.563161  │ -0.48732   │ -2.09803  │
│ 14  │ "A"   │ 0.350383  │ -0.172319  │ 1.02911   │
│ 15  │ "A"   │ 0.229074  │ 1.56088    │ 1.24288   │

In [71]:
sort!(df8, cols = [:Group, :variable1], rev = false)

15×4 DataFrames.DataFrame
│ Row │ Group │ variable1 │ variable2  │ Variable3 │
├─────┼───────┼───────────┼────────────┼───────────┤
│ 1   │ "A"   │ 0.229074  │ 1.56088    │ 1.24288   │
│ 2   │ "A"   │ 0.350383  │ -0.172319  │ 1.02911   │
│ 3   │ "A"   │ 0.563161  │ -0.48732   │ -2.09803  │
│ 4   │ "A"   │ 1.4757    │ -0.722768  │ -0.555648 │
│ 5   │ "A"   │ 2.92004   │ -1.59193   │ 2.18142   │
│ 6   │ "B"   │ -2.20212  │ 0.62961    │ -1.15986  │
│ 7   │ "B"   │ -0.934414 │ -0.261611  │ 0.307004  │
│ 8   │ "B"   │ -0.649502 │ -0.302059  │ 0.628162  │
│ 9   │ "B"   │ -0.416821 │ -0.0698572 │ -0.373174 │
│ 10  │ "B"   │ 0.805701  │ -0.858425  │ -0.283685 │
│ 11  │ "B"   │ 1.22855   │ 1.32844    │ 0.579553  │
│ 12  │ "C"   │ 0.0289819 │ -0.346787  │ 1.71514   │
│ 13  │ "C"   │ 0.270719  │ -0.159861  │ 1.47013   │
│ 14  │ "C"   │ 0.614097  │ 1.27636    │ -1.19903  │
│ 15  │ "C"   │ 0.726106  │ 0.892031   │ -0.36738  │

In [73]:
sort!(df8, cols = [:Group, :variable1, :variable2], rev = (false, false, true))

15×4 DataFrames.DataFrame
│ Row │ Group │ variable1 │ variable2  │ Variable3 │
├─────┼───────┼───────────┼────────────┼───────────┤
│ 1   │ "A"   │ 0.229074  │ 1.56088    │ 1.24288   │
│ 2   │ "A"   │ 0.350383  │ -0.172319  │ 1.02911   │
│ 3   │ "A"   │ 0.563161  │ -0.48732   │ -2.09803  │
│ 4   │ "A"   │ 1.4757    │ -0.722768  │ -0.555648 │
│ 5   │ "A"   │ 2.92004   │ -1.59193   │ 2.18142   │
│ 6   │ "B"   │ -2.20212  │ 0.62961    │ -1.15986  │
│ 7   │ "B"   │ -0.934414 │ -0.261611  │ 0.307004  │
│ 8   │ "B"   │ -0.649502 │ -0.302059  │ 0.628162  │
│ 9   │ "B"   │ -0.416821 │ -0.0698572 │ -0.373174 │
│ 10  │ "B"   │ 0.805701  │ -0.858425  │ -0.283685 │
│ 11  │ "B"   │ 1.22855   │ 1.32844    │ 0.579553  │
│ 12  │ "C"   │ 0.0289819 │ -0.346787  │ 1.71514   │
│ 13  │ "C"   │ 0.270719  │ -0.159861  │ 1.47013   │
│ 14  │ "C"   │ 0.614097  │ 1.27636    │ -1.19903  │
│ 15  │ "C"   │ 0.726106  │ 0.892031   │ -0.36738  │

In [74]:
df9 = DataFrame(A = [1, 2, 2, 3, 4, 5], B = [11, 12, 12, 13 ,14, 15], C = ["A", "B", "B", "C", "D", "E"])

6×3 DataFrames.DataFrame
│ Row │ A │ B  │ C   │
├─────┼───┼────┼─────┤
│ 1   │ 1 │ 11 │ "A" │
│ 2   │ 2 │ 12 │ "B" │
│ 3   │ 2 │ 12 │ "B" │
│ 4   │ 3 │ 13 │ "C" │
│ 5   │ 4 │ 14 │ "D" │
│ 6   │ 5 │ 15 │ "E" │

In [75]:
unique(df9)

5×3 DataFrames.DataFrame
│ Row │ A │ B  │ C   │
├─────┼───┼────┼─────┤
│ 1   │ 1 │ 11 │ "A" │
│ 2   │ 2 │ 12 │ "B" │
│ 3   │ 3 │ 13 │ "C" │
│ 4   │ 4 │ 14 │ "D" │
│ 5   │ 5 │ 15 │ "E" │

In [76]:
df10 = DataFrame(A = 1:10, B = 11:20, C = 21:30)

10×3 DataFrames.DataFrame
│ Row │ A  │ B  │ C  │
├─────┼────┼────┼────┤
│ 1   │ 1  │ 11 │ 21 │
│ 2   │ 2  │ 12 │ 22 │
│ 3   │ 3  │ 13 │ 23 │
│ 4   │ 4  │ 14 │ 24 │
│ 5   │ 5  │ 15 │ 25 │
│ 6   │ 6  │ 16 │ 26 │
│ 7   │ 7  │ 17 │ 27 │
│ 8   │ 8  │ 18 │ 28 │
│ 9   │ 9  │ 19 │ 29 │
│ 10  │ 10 │ 20 │ 30 │

In [77]:
df10[3, :B]

13

In [78]:
complete_cases(df10)

10-element BitArray{1}:
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true

In [79]:
complete_cases!(df10)

10×3 DataFrames.DataFrame
│ Row │ A  │ B  │ C  │
├─────┼────┼────┼────┤
│ 1   │ 1  │ 11 │ 21 │
│ 2   │ 2  │ 12 │ 22 │
│ 3   │ 3  │ 13 │ 23 │
│ 4   │ 4  │ 14 │ 24 │
│ 5   │ 5  │ 15 │ 25 │
│ 6   │ 6  │ 16 │ 26 │
│ 7   │ 7  │ 17 │ 27 │
│ 8   │ 8  │ 18 │ 28 │
│ 9   │ 9  │ 19 │ 29 │
│ 10  │ 10 │ 20 │ 30 │

In [80]:
df10[3, :A] = NA
df10[4, :B] = NA
df10[[3, 9], :C] = NA

NA

In [81]:
isna(df10[:A])

10-element BitArray{1}:
 false
 false
  true
 false
 false
 false
 false
 false
 false
 false

In [82]:
findin(isna(df10[:A]), true)

1-element Array{Int64,1}:
 3

In [83]:
rows, cols = size(df10)

(10,3)

In [145]:
for i in 1:cols
    deleterows!(df10, find(isna(df10[:, i])))
end

In [146]:
df10

7×3 DataFrames.DataFrame
│ Row │ A  │ B  │ C  │
├─────┼────┼────┼────┤
│ 1   │ 1  │ 11 │ 21 │
│ 2   │ 2  │ 12 │ 22 │
│ 3   │ 5  │ 15 │ 25 │
│ 4   │ 6  │ 16 │ 26 │
│ 5   │ 7  │ 17 │ 27 │
│ 6   │ 8  │ 18 │ 28 │
│ 7   │ 10 │ 20 │ 30 │

In [90]:
df11 = DataFrame(x = 1:10, y = rand(10), z = rand(["c", "x","r"]))

10×3 DataFrames.DataFrame
│ Row │ x  │ y        │ z   │
├─────┼────┼──────────┼─────┤
│ 1   │ 1  │ 0.844233 │ "c" │
│ 2   │ 2  │ 0.213131 │ "c" │
│ 3   │ 3  │ 0.517708 │ "c" │
│ 4   │ 4  │ 0.179342 │ "c" │
│ 5   │ 5  │ 0.311523 │ "c" │
│ 6   │ 6  │ 0.664827 │ "c" │
│ 7   │ 7  │ 0.828614 │ "c" │
│ 8   │ 8  │ 0.507599 │ "c" │
│ 9   │ 9  │ 0.851793 │ "c" │
│ 10  │ 10 │ 0.722212 │ "c" │

In [91]:
rename!(df11, Dict(:x => :a, :y => :b, :z => :c))

10×3 DataFrames.DataFrame
│ Row │ a  │ b        │ c   │
├─────┼────┼──────────┼─────┤
│ 1   │ 1  │ 0.844233 │ "c" │
│ 2   │ 2  │ 0.213131 │ "c" │
│ 3   │ 3  │ 0.517708 │ "c" │
│ 4   │ 4  │ 0.179342 │ "c" │
│ 5   │ 5  │ 0.311523 │ "c" │
│ 6   │ 6  │ 0.664827 │ "c" │
│ 7   │ 7  │ 0.828614 │ "c" │
│ 8   │ 8  │ 0.507599 │ "c" │
│ 9   │ 9  │ 0.851793 │ "c" │
│ 10  │ 10 │ 0.722212 │ "c" │

In [92]:
names!(df11, [:A, :B, :C])

10×3 DataFrames.DataFrame
│ Row │ A  │ B        │ C   │
├─────┼────┼──────────┼─────┤
│ 1   │ 1  │ 0.844233 │ "c" │
│ 2   │ 2  │ 0.213131 │ "c" │
│ 3   │ 3  │ 0.517708 │ "c" │
│ 4   │ 4  │ 0.179342 │ "c" │
│ 5   │ 5  │ 0.311523 │ "c" │
│ 6   │ 6  │ 0.664827 │ "c" │
│ 7   │ 7  │ 0.828614 │ "c" │
│ 8   │ 8  │ 0.507599 │ "c" │
│ 9   │ 9  │ 0.851793 │ "c" │
│ 10  │ 10 │ 0.722212 │ "c" │

In [93]:
array_a = convert(Array, df11[:A])

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [94]:
?residuals

search: residuals df_residual dof_residual



No documentation found.

`StatsBase.residuals` is a generic `Function`.

```julia
# 2 methods for generic function "residuals":
residuals(::DataFrames.DataFrameRegressionModel{M,T}, ...) at /Users/bradley/.julia/v0.4/DataFrames/src/statsmodels/statsmodel.jl:27
residuals(obj::StatsBase.RegressionModel) at /Users/bradley/.julia/v0.4/StatsBase/src/statmodels.jl:152
```


In [95]:
residuals(df10)

LoadError: LoadError: MethodError: `residuals` has no method matching residuals(::DataFrames.DataFrame)
while loading In[95], in expression starting on line 1

In [96]:
?DataFrameRegressionModel

search:

Couldn't find DataFrameRegressionModel
Perhaps you meant RegressionModel


LoadError: LoadError: "DataFrameRegressionModel" is not defined in module Main
while loading In[96], in expression starting on line 119

In [97]:
?RegressionModel

search: RegressionModel



No documentation found.

**Summary:**

```julia
abstract StatsBase.RegressionModel <: StatsBase.StatisticalModel
```

**Subtypes:**

```julia
DataFrames.DataFrameRegressionModel{M,T}
```


In [98]:
regressionmodel

LoadError: LoadError: UndefVarError: regressionmodel not defined
while loading In[98], in expression starting on line 1

In [99]:
?regression

search: RegressionModel

Couldn't find regression
Perhaps you meant precision


LoadError: LoadError: "regression" is not defined in module Main
while loading In[99], in expression starting on line 119

In [100]:
using Distributions

INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Distributions.ji for module Distributions.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/PDMats.ji for module PDMats.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Rmath.ji for module Rmath.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/StatsFuns.ji for module StatsFuns.


In [101]:
using Plots
plotlyjs()

INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Plots.ji for module Plots.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/FixedSizeArrays.ji for module FixedSizeArrays.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/FixedPointNumbers.ji for module FixedPointNumbers.
    floattype(Type{#T<:FixedPointNumbers.Fixed}) at /Users/bradley/.julia/v0.4/FixedPointNumbers/src/fixed.jl:16
is ambiguous with: 
    floattype(Type{FixedPointNumbers.FixedPoint{#T<:Union{Int8, UInt16, Int16, UInt8}, #f<:Any}}) at /Users/bradley/.julia/v0.4/FixedPointNumbers/src/FixedPointNumbers.jl:89.
To fix, define 
    floattype(Type{FixedPointNumbers.Fixed{_<:Union{Int8, Int16}, #f<:Any}})
before the new definition.
    floattype(Type{#T<:FixedPointNumbers.UFixed}) at /Users/bradley/.julia/v0.4/FixedPointNumbers/src/ufixed.jl:14
is ambiguous with: 
    floattype(Type{FixedPointNumbers.FixedPoint{#T<:Union{Int8, UInt16, Int16, UInt8}, #f<:Any}}) at /Users/bradle

Plots.PlotlyJSBackend()

In [102]:
using StatPlots

LoadError: LoadError: ArgumentError: StatPlots not found in path
while loading In[102], in expression starting on line 1

In [103]:
Pkg.add("StatPlots")

INFO: Cloning cache of StatPlots from git://github.com/JuliaPlots/StatPlots.jl.git
INFO: Installing StatPlots v0.0.3
INFO: Building Rmath
INFO: Building Plots
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of StatPlots
INFO: Use `Pkg.update()` to get the latest versions of your packages


In [104]:
Pkg.add("HypothesisTests")

INFO: Cloning cache of Combinatorics from git://github.com/JuliaMath/Combinatorics.jl.git
INFO: Cloning cache of HypothesisTests from git://github.com/JuliaStats/HypothesisTests.jl.git
INFO: Cloning cache of Roots from git://github.com/JuliaMath/Roots.jl.git
INFO: Installing Combinatorics v0.2.1
INFO: Installing HypothesisTests v0.4.0
INFO: Installing Roots v0.2.1
INFO: Building Rmath
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of HypothesisTests
INFO: Use `Pkg.update()` to get the latest versions of your packages


In [105]:
Pkg.add("GLM")

INFO: Cloning cache of GLM from git://github.com/JuliaStats/GLM.jl.git
INFO: Installing GLM v0.5.6
INFO: Building Rmath
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of GLM
INFO: Use `Pkg.update()` to get the latest versions of your packages


In [106]:
Pkg.update()

INFO: Updating METADATA...
INFO: Updating cache of DataFrames...
INFO: Updating cache of ForwardDiff...
INFO: Updating cache of DataFrames...
INFO: Computing changes...
INFO: No packages to install, update or remove


In [107]:
using StatPlots
using HypothesisTests
using GLM

INFO: Precompiling module StatPlots...
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/KernelDensity.ji for module KernelDensity.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/NaNMath.ji for module NaNMath.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Optim.ji for module Optim.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Calculus.ji for module Calculus.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/PositiveFactorizations.ji for module PositiveFactorizations.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/ForwardDiff.ji for module ForwardDiff.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Ratios.ji for module Ratios.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Interpolations.ji for module Interpolations.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/WoodburyMatrices.ji for module WoodburyMatrices.
INFO: Reco

In [108]:
norm1 = randn(1000);

In [111]:
histogram(norm1, bins = 10, label = "Standard normal distribution",
title = "Histogram")

In [112]:
mean(norm1)

0.06330705794220443

In [113]:
norm2 = rand(Normal(0, 1), 1000);

In [114]:
histogram(norm2, bins = 10, label = "Standard normal distribution", title = "Histogram")

In [115]:
plot(Normal(0, 1), fill = (0.5, :blue), label = "Standard normal distribution", title = "Density")

In [117]:
fit(Normal, norm1)

Distributions.Normal{Float64}(μ=0.06330705794220436, σ=0.9867749322368125)

In [118]:
plot(Chisq(3), fill = (0.25, :blue), label = "3 deg. of freedom")

In [119]:
plot!(Chisq(5), fill = (0.25, :orange), label = "5 deg. of freedom")

In [120]:
plot!(Chisq(10), fill = (0.25, :deepskyblue), label = "10 deg. of freedom")

In [121]:
plot(Exponential(2), fill = (0.25, :blue), label = "Scale parameter 2")

In [122]:
plot!(Exponential(4), fill = (0.25, :orange), label = "4")

In [123]:
plot!(Exponential(6), fill = (0.25, :deepskyblue), label = "6")

In [124]:
readtable("data1.csv")

120×6 DataFrames.DataFrame
│ Row │ PatientID │ Cat1 │ Cat2 │ Var1    │ Var2    │ Var3    │
├─────┼───────────┼──────┼──────┼─────────┼─────────┼─────────┤
│ 1   │ 1         │ "A"  │ "C"  │ 38.2568 │ 5.93913 │ 35.0579 │
│ 2   │ 2         │ "A"  │ "C"  │ 17.8317 │ 5.34754 │ 21.131  │
│ 3   │ 8         │ "A"  │ "B"  │ 16.0218 │ 6.60709 │ 60.9436 │
│ 4   │ 9         │ "A"  │ "C"  │ 45.1158 │ 6.00733 │ 21.8797 │
│ 5   │ 16        │ "A"  │ "C"  │ 20.448  │ 8.54819 │ 20.6623 │
│ 6   │ 18        │ "A"  │ "B"  │ 28.3549 │ 7.95642 │ 33.1807 │
│ 7   │ 25        │ "A"  │ "C"  │ 22.4497 │ 6.34618 │ 40.2365 │
│ 8   │ 28        │ "A"  │ "B"  │ 48.4125 │ 5.32583 │ 28.8956 │
│ 9   │ 29        │ "A"  │ "C"  │ 40.0075 │ 11.4189 │ 71.5911 │
│ 10  │ 33        │ "A"  │ "C"  │ 20.7181 │ 5.37768 │ 27.4216 │
│ 11  │ 37        │ "A"  │ "B"  │ 17.0396 │ 5.34168 │ 24.3501 │
⋮
│ 109 │ 76        │ "B"  │ "R"  │ 17.0029 │ 5.39477 │ 31.1297 │
│ 110 │ 78        │ "B"  │ "L"  │ 55.3879 │ 4.15304 │ 40.0846 │
│ 111 │ 80        │ "B"  │ "R"  │ 20.2205 │ 6.36442 │ 45.435  │
│ 112 │ 83        │ "B"  │ "L"  │ 16.4172 │ 3.84167 │ 89.6969 │
│ 113 │ 84        │ "B"  │ "R"  │ 47.6224 │ 5.40032 │ 47.4541 │
│ 114 │ 86        │ "B"  │ "L"  │ 73.0229 │ 3.38349 │ 55.1737 │
│ 115 │ 92        │ "B"  │ "R"  │ 16.4106 │ 4.30351 │ 87.7357 │
│ 116 │ 95        │ "B"  │ "R"  │ 16.2801 │ 3.37252 │ 52.6018 │
│ 117 │ 101       │ "B"  │ "L"  │ 16.8883 │ 3.19598 │ 60.1883 │
│ 118 │ 113       │ "B"  │ "R"  │ 32.3537 │ 3.38677 │ 30.0157 │
│ 119 │ 115       │ "B"  │ "R"  │ 20.1379 │ 3.42731 │ 44.6893 │
│ 120 │ 119       │ "B"  │ "L"  │ 17.6144 │ 3.45116 │ 40.6947 │

In [126]:
df = DataFrame(Group = rand(["A", "B"], 20), Variable1 = randn(20), Variable2 = rand(20))

20×3 DataFrames.DataFrame
│ Row │ Group │ Variable1 │ Variable2 │
├─────┼───────┼───────────┼───────────┤
│ 1   │ "B"   │ 0.220405  │ 0.787355  │
│ 2   │ "B"   │ -0.548794 │ 0.964987  │
│ 3   │ "B"   │ -0.993461 │ 0.103557  │
│ 4   │ "B"   │ 2.16997   │ 0.463139  │
│ 5   │ "B"   │ -0.611708 │ 0.570016  │
│ 6   │ "B"   │ 0.369533  │ 0.892206  │
│ 7   │ "A"   │ -1.631    │ 0.913496  │
│ 8   │ "B"   │ 0.66111   │ 0.856828  │
│ 9   │ "A"   │ 1.31695   │ 0.104467  │
│ 10  │ "A"   │ 1.04944   │ 0.536613  │
│ 11  │ "A"   │ -1.37123  │ 0.181614  │
│ 12  │ "A"   │ -1.82556  │ 0.0599865 │
│ 13  │ "A"   │ -0.431066 │ 0.870084  │
│ 14  │ "A"   │ 0.221629  │ 0.83778   │
│ 15  │ "B"   │ -2.10314  │ 0.422977  │
│ 16  │ "A"   │ -0.325857 │ 0.909081  │
│ 17  │ "B"   │ -1.05521  │ 0.360373  │
│ 18  │ "B"   │ -2.12532  │ 0.987334  │
│ 19  │ "B"   │ 0.63061   │ 0.528687  │
│ 20  │ "B"   │ 0.966504  │ 0.230373  │

In [127]:
deleterows!(df, [3, 5, 9])

17×3 DataFrames.DataFrame
│ Row │ Group │ Variable1 │ Variable2 │
├─────┼───────┼───────────┼───────────┤
│ 1   │ "B"   │ 0.220405  │ 0.787355  │
│ 2   │ "B"   │ -0.548794 │ 0.964987  │
│ 3   │ "B"   │ 2.16997   │ 0.463139  │
│ 4   │ "B"   │ 0.369533  │ 0.892206  │
│ 5   │ "A"   │ -1.631    │ 0.913496  │
│ 6   │ "B"   │ 0.66111   │ 0.856828  │
│ 7   │ "A"   │ 1.04944   │ 0.536613  │
│ 8   │ "A"   │ -1.37123  │ 0.181614  │
│ 9   │ "A"   │ -1.82556  │ 0.0599865 │
│ 10  │ "A"   │ -0.431066 │ 0.870084  │
│ 11  │ "A"   │ 0.221629  │ 0.83778   │
│ 12  │ "B"   │ -2.10314  │ 0.422977  │
│ 13  │ "A"   │ -0.325857 │ 0.909081  │
│ 14  │ "B"   │ -1.05521  │ 0.360373  │
│ 15  │ "B"   │ -2.12532  │ 0.987334  │
│ 16  │ "B"   │ 0.63061   │ 0.528687  │
│ 17  │ "B"   │ 0.966504  │ 0.230373  │

In [128]:
sub(df[3,:])

LoadError: LoadError: MethodError: `sub` has no method matching sub(::DataFrames.DataFrame)
Closest candidates are:
  sub(::DataFrames.DataFrame, !Matched::AbstractArray{Bool,1})
  sub{S<:Real}(::DataFrames.DataFrame, !Matched::AbstractArray{S<:Real,1})
  sub(::DataFrames.AbstractDataFrame, !Matched::Integer)
  ...
while loading In[128], in expression starting on line 1

In [129]:
sub(df[3])

LoadError: LoadError: BoundsError: attempt to access (17,)
  at index [0]
while loading In[129], in expression starting on line 1

In [130]:
sub(df[1])

LoadError: LoadError: BoundsError: attempt to access (17,)
  at index [0]
while loading In[130], in expression starting on line 1

In [132]:
sub(df[3, 3])

LoadError: LoadError: MethodError: `sub` has no method matching sub(::Float64)
while loading In[132], in expression starting on line 1

In [133]:
sub(df, 3)

1×3 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ Group │ Variable1 │ Variable2 │
├─────┼───────┼───────────┼───────────┤
│ 1   │ "B"   │ 2.16997   │ 0.463139  │

In [134]:
?rand

search: rand rand! randn randn! randexp randperm randjump randexp! randbool



```
rand([rng], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:n` or `['x','y','z']`), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to `BigInt`), and to $[0, 1)$ for floating point numbers;

`S` defaults to `Float64`.


In [135]:
?var

search: var varm Vararg varlogx variation VariateForm NewvarNode Univariate



```
var(v[, region])
```

Compute the sample variance of a vector or array `v`, optionally along dimensions in `region`. The algorithm will return an estimator of the generative distribution's variance under the assumption that each entry of `v` is an IID drawn from that generative distribution. This computation is equivalent to calculating `sumabs2(v - mean(v)) / (length(v) - 1)`. Note: Julia does not ignore `NaN` values in the computation. For applications requiring the handling of missing data, the `DataArray` package is recommended.

```
var(x, wv::WeightVec, [dim]; mean=nothing)
```

Return the variance of a real-valued array `x`, optionally over a dimension `dim`. The weighting vector `wv` specifies frequency weights (also called case weights) for the estimate.

This function differs from its counterpart in Base in that Bessel's correction is not used. That is, here the denominator for the variance is `sum(wv)`, whereas it's `length(x)-1` in `Base.var`. The impact is that this is not a weighted estimate of the population variance based on the sample; it's the weighted variance of the sample.


In [136]:
length(df)

3

In [138]:
?fill

search: fill fill! finally filt filt! filter filter! Filter FileIO filesize



```
fill(x, dims)
```

Create an array filled with the value `x`. For example, `fill(1.0, (10,10))` returns a 10x10 array of floats, with each element initialized to `1.0`.

If `x` is an object reference, all elements will refer to the same object. `fill(Foo(), dims)` will return an array filled with the result of evaluating `Foo()` once.


In [142]:
?hcat

search: hcat hvcat showcompact FisherTLinearAssociation



```
hcat(A...)
```

Concatenate along dimension 2


In [140]:
?hvcat

search: hvcat



```
hvcat(rows::Tuple{Vararg{Int}}, values...)
```

Horizontal and vertical concatenation in one call. This function is called for block matrix syntax. The first argument specifies the number of arguments to concatenate in each block row.

```jldoctest
julia> a, b, c, d, e, f = 1, 2, 3, 4, 5, 6
(1,2,3,4,5,6)

julia> [a b c; d e f]
2x3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> hvcat((3,3), a,b,c,d,e,f)
2x3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> [a b;c d; e f]
3x2 Array{Int64,2}:
 1  2
 3  4
 5  6

julia> hvcat((2,2,2), a,b,c,d,e,f)
3x2 Array{Int64,2}:
 1  2
 3  4
 5  6
```

If the first argument is a single integer `n`, then all block rows are assumed to have `n` block columns.
