In [1]:
using DataFrames

INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/SortingAlgorithms.ji for module SortingAlgorithms.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/DataFrames.ji for module DataFrames.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/StatsBase.ji for module StatsBase.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/DataArrays.ji for module DataArrays.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/GZip.ji for module GZip.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/FileIO.ji for module FileIO.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/MacroTools.ji for module MacroTools.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Juno.ji for module Juno.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Media.ji for module Media.
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/Hiccup.ji for module Hiccup.
INFO: Re

In [2]:
array1 = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [3]:
array2 = [1 2 3]

1x3 Array{Int64,2}:
 1  2  3

In [4]:
transpose(array1)

1x3 Array{Int64,2}:
 1  2  3

In [5]:
array1

3-element Array{Int64,1}:
 1
 2
 3

In [6]:
array1 == array2

false

In [7]:
transpose(array1) == array2

true

In [8]:
array1'

1x3 Array{Int64,2}:
 1  2  3

In [9]:
array1' == array2

true

In [10]:
`array

LoadError: LoadError: syntax: incomplete: invalid "`" syntax
while loading In[10], in expression starting on line 1

In [11]:
`(1 2 3)

LoadError: LoadError: syntax: incomplete: invalid "`" syntax
while loading In[11], in expression starting on line 1

In [13]:
array3 = [1, 2, 3.0]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [18]:
array4 = [[1,2,3] [4,5,6] [7,8,9]]

3x3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [19]:
array5 = [[1 2 3]; [4 5 6]; [7 8 9]]

3x3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [20]:
length(array5)

9

In [22]:
for i in 1:length(array5)
    println("Element $(i) is ", array5[i])
end

Element 1 is 1
Element 2 is 4
Element 3 is 7
Element 4 is 2
Element 5 is 5
Element 6 is 8
Element 7 is 3
Element 8 is 6
Element 9 is 9


In [23]:
array4' == array5

true

In [24]:
array4'

3x3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [25]:
repmat([1, 2], 3)

6-element Array{Int64,1}:
 1
 2
 1
 2
 1
 2

In [26]:
repmat([1 2], 3)

3x2 Array{Int64,2}:
 1  2
 1  2
 1  2

In [27]:
eye(3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [28]:
linspace(0, 10, 11)

linspace(0.0,10.0,11)

In [29]:
array6 = collect(linspace(0, 10, 11))

11-element Array{Float64,1}:
  0.0
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [30]:
array7 = collect(logspace(2, 3))

50-element Array{Float64,1}:
  100.0  
  104.811
  109.854
  115.14 
  120.679
  126.486
  132.571
  138.95 
  145.635
  152.642
  159.986
  167.683
  175.751
    ⋮    
  596.362
  625.055
  655.129
  686.649
  719.686
  754.312
  790.604
  828.643
  868.511
  910.298
  954.095
 1000.0  

In [31]:
array8 = collect(range(0, 2, 10))

10-element Array{Int64,1}:
  0
  2
  4
  6
  8
 10
 12
 14
 16
 18

In [32]:
array9 = collect(0:1:5)

6-element Array{Int64,1}:
 0
 1
 2
 3
 4
 5

In [33]:
typeof(0:1:5)

StepRange{Int64,Int64}

In [34]:
typeof(0:1)

UnitRange{Int64}

In [35]:
array10 = Array(Integer, 3, 3)

3x3 Array{Integer,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef
 #undef  #undef  #undef

In [36]:
array11 = Array(Int64, 3, 3)

3x3 Array{Int64,2}:
 4189022137156394855  7958535038077905954  7957695011148363298
 7310597164893758754  8319593519717379425  3180157261895055906
 8391162085809418847  3180215807337460325  7957695011165139746

In [37]:
array8

10-element Array{Int64,1}:
  0
  2
  4
  6
  8
 10
 12
 14
 16
 18

In [38]:
reshape(array8, 2, 5)

2x5 Array{Int64,2}:
 0  4   8  12  16
 2  6  10  14  18

In [39]:
array12 = rand(10:20, 10, 5)

10x5 Array{Int64,2}:
 13  20  18  15  13
 16  17  10  13  17
 10  17  11  12  12
 17  10  20  11  13
 14  11  10  17  20
 20  13  10  16  16
 17  13  10  10  18
 13  12  18  17  11
 18  11  13  17  19
 12  14  19  11  20

In [40]:
array12[:, 2]

10-element Array{Int64,1}:
 20
 17
 17
 10
 11
 13
 13
 12
 11
 14

In [41]:
array12[:, [2, 5]]

10x2 Array{Int64,2}:
 20  13
 17  17
 17  12
 10  13
 11  20
 13  16
 13  18
 12  11
 11  19
 14  20

In [42]:
array12[[2, 4, 6], [1, 5]]

3x2 Array{Int64,2}:
 16  17
 17  13
 20  16

In [43]:
array12[1, 3:end]

1x3 Array{Int64,2}:
 18  15  13

In [44]:
array12[:, 1] .> 12

10-element BitArray{1}:
  true
  true
 false
  true
  true
  true
  true
  true
  true
 false

In [45]:
find(array12[:, 1] .> 12)

8-element Array{Int64,1}:
 1
 2
 4
 5
 6
 7
 8
 9

In [46]:
array13 = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [47]:
push!(array13, 5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [48]:
unshift!(array13, 0)

6-element Array{Int64,1}:
 0
 1
 2
 3
 4
 5

In [49]:
array14 = []

0-element Array{Any,1}

In [50]:
for i in 1:5
    push!(array14, 3 * i)
end

In [51]:
array14

5-element Array{Any,1}:
  3
  6
  9
 12
 15

In [52]:
array15 = [3 * i for i in 1:5]

5-element Array{Int64,1}:
  3
  6
  9
 12
 15

In [53]:
array14 == array15

true

In [54]:
[n^2 for n in 1:3]

3-element Array{Int64,1}:
 1
 4
 9

In [55]:
[a * b for a in 1:3, b in 1:3]

3x3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

In [57]:
sum(array15)

45

In [58]:
std(array15)

4.743416490252569

In [59]:
mean(array15)

9.0

In [63]:
array16 = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [64]:
5 + array16

3-element Array{Int64,1}:
 6
 7
 8

In [66]:
3 * array16

3-element Array{Int64,1}:
 3
 6
 9

In [67]:
array17 = [4, 5, 6]

3-element Array{Int64,1}:
 4
 5
 6

In [68]:
array16 + array17

3-element Array{Int64,1}:
 5
 7
 9

In [69]:
array16 * array17

LoadError: LoadError: MethodError: `*` has no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
  *{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(!Matched::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, ::Union{DenseArray{S,1},SubArray{S,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  *{TA,TB}(!Matched::Base.LinAlg.AbstractTriangular{TA,S<:AbstractArray{T,2}}, ::Union{DenseArray{TB,1},DenseArray{TB,2},SubArray{TB,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD},SubArray{TB,2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  ...
while loading In[69], in expression starting on line 1

In [70]:
array16 .* array17

3-element Array{Int64,1}:
  4
 10
 18

In [71]:
transpose(array16) * array17

1-element Array{Int64,1}:
 32

In [72]:
[a + b * c for a in 1:3, b in 1:3, c in 1:3]

3x3x3 Array{Int64,3}:
[:, :, 1] =
 2  3  4
 3  4  5
 4  5  6

[:, :, 2] =
 3  5  7
 4  6  8
 5  7  9

[:, :, 3] =
 4  7  10
 5  8  11
 6  9  12

In [73]:
typeof(NaN)

Float64

In [74]:
NaN == NaN

false

In [75]:
array18 = [1, 2, NaN, 4, 5]

5-element Array{Float64,1}:
   1.0
   2.0
 NaN  
   4.0
   5.0

In [76]:
sum(array18)

NaN

In [77]:
isnan(array18)

5-element Array{Bool,1}:
 false
 false
  true
 false
 false

In [78]:
array19 = @data([1, 2, 3, 4, NA, 7, NA, 2])

8-element DataArrays.DataArray{Int64,1}:
 1  
 2  
 3  
 4  
  NA
 7  
  NA
 2  

In [79]:
array19_clean = dropna(array19)

6-element Array{Int64,1}:
 1
 2
 3
 4
 7
 2

In [80]:
using RCall

INFO: Precompiling module RCall...
INFO: Recompiling stale cache file /Users/bradley/.julia/lib/v0.4/DataStructures.ji for module DataStructures.


R installation found at "/Library/Frameworks/R.framework/Resources"


In [81]:
?@

LoadError: LoadError: syntax: incomplete: premature end of input
while loading In[81], in expression starting on line 1

In [82]:
?@data

No documentation found.

```julia
@data(ex)
```


In [83]:
?macro

search: macro macroexpand MacroTools mean_and_cov



`macro` defines a method to include generated code in the final body of a program. A macro maps a tuple of arguments to a returned expression, and the resulting expression is compiled directly rather than requiring a runtime `eval()` call. Macro arguments may include expressions, literal values, and symbols. For example:

```
macro sayhello(name)
    return :( println("Hello, ", $name) )
end
```

This macro takes one argument: `name`. When `@sayhello` is encountered, the quoted expression is expanded to interpolate the value of the argument into the final expression.


In [84]:
tup = (1, 2, 3, "hello")

(1,2,3,"hello")

In [85]:
typeof(tup)

Tuple{Int64,Int64,Int64,ASCIIString}

In [87]:
for i in 1:length(tup)
    println("The value of the tuple at the index $(i) is $(tup[i]) and the type is $(typeof(tup[i])).")
end

The value of the tuple at the index 1 is 1 and the type is Int64.
The value of the tuple at the index 2 is 2 and the type is Int64.
The value of the tuple at the index 3 is 3 and the type is Int64.
The value of the tuple at the index 4 is hello and the type is ASCIIString.


In [88]:
a, b, c, seven = (1, 2, 3, 7)

(1,2,3,7)

In [89]:
a

1

In [90]:
seven

7

In [91]:
b

2

In [92]:
c

3

In [93]:
tup2 = (1, 3, 5, 7, 9, 11, 13, 15)

(1,3,5,7,9,11,13,15)

In [94]:
tup2[end]

15

In [95]:
tup2[2:4]

(3,5,7)

In [96]:
tup2[end:-1:1]

(15,13,11,9,7,5,3,1)

In [97]:
tup3 = ((1, 2, 3), 1, 2, (3, 100, 1))

((1,2,3),1,2,(3,100,1))

In [98]:
tup3[1]

(1,2,3)

In [99]:
tup3[2]

1

In [101]:
tup3[1][2]

2

In [102]:
tup3[4][2]

100

In [105]:
dict1 = Dict(1 => 77, 2 => 66, 3 => 1)

Dict{Int64,Int64} with 3 entries:
  2 => 66
  3 => 1
  1 => 77

In [106]:
dict1 = Dict(Pair(1, 100), Pair(2, 200), Pair(3, 300))

Dict{Int64,Int64} with 3 entries:
  2 => 200
  3 => 300
  1 => 100

In [107]:
dict2 = Dict{Any, Any}("a" => 1, (2, 3) => "hello")

Dict{Any,Any} with 2 entries:
  (2,3) => "hello"
  "a"   => 1

In [108]:
dict2

Dict{Any,Any} with 2 entries:
  (2,3) => "hello"
  "a"   => 1

In [109]:
dict4 = Dict(:A => 300, :B => 305, :C => 309)

Dict{Symbol,Int64} with 3 entries:
  :C => 309
  :B => 305
  :A => 300

In [110]:
dict4[:B]

305

In [111]:
get(dict4, :H, "That key does not exist!")

"That key does not exist!"

In [112]:
get(dict4, :B, "That key does not exist!")

305

In [113]:
in((:A => 300), dict4)

true

In [114]:
haskey(dict4, :D)

false

In [115]:
dict4[:D] = 301

301

In [116]:
dict4

Dict{Symbol,Int64} with 4 entries:
  :C => 309
  :B => 305
  :A => 300
  :D => 301

In [119]:
hash(dict4)

0x673e52e29366b6a1

In [120]:
delete!(dict4, :A)

Dict{Symbol,Int64} with 3 entries:
  :C => 309
  :B => 305
  :D => 301

In [121]:
keys(dict4)

Base.KeyIterator for a Dict{Symbol,Int64} with 3 entries. Keys:
  :C
  :B
  :D

In [122]:
values(dict4)

Base.ValueIterator for a Dict{Symbol,Int64} with 3 entries. Values:
  309
  305
  301

In [123]:
length(dict4)

3

In [125]:
for (k, v) in dict4
    println("The key $(k) has a value $(v).")
end

The key C has a value 309.
The key B has a value 305.
The key D has a value 301.


In [126]:
procedure_vals = ["Appendectomy", "Colectomy", "Cholecystectomy"]
procedure_dict = Dict{AbstractString, AbstractString}()

Dict{AbstractString,AbstractString} with 0 entries

In [128]:
for (s, n) in enumerate(procedure_vals)
    procedure_dict["x_$(s)"] = n
end

In [129]:
procedure_dict

Dict{AbstractString,AbstractString} with 3 entries:
  "x_1" => "Appendectomy"
  "x_2" => "Colectomy"
  "x_3" => "Cholecystectomy"

In [131]:
for (k, v) in procedure_dict
    println(k, " is ", v)
end

x_1 is Appendectomy
x_2 is Colectomy
x_3 is Cholecystectomy


In [132]:
dict5 = Dict{AbstractString, Int16}("a" => 1, "b" => 2, "c" => 3, "d" => 4, "e" => 5)

Dict{AbstractString,Int16} with 5 entries:
  "c" => 3
  "e" => 5
  "b" => 2
  "a" => 1
  "d" => 4

In [133]:
for k in sort(collect(keys(dict5)))
    println("$(k) is $(dict5[k])")
end

a is 1
b is 2
c is 3
d is 4
e is 5


In [134]:
keys(dict5)

Base.KeyIterator for a Dict{AbstractString,Int16} with 5 entries. Keys:
  "c"
  "e"
  "b"
  "a"
  "d"

In [135]:
collect(keys(dict5))

5-element Array{AbstractString,1}:
 "c"
 "e"
 "b"
 "a"
 "d"

In [136]:
sort(collect(keys(dict5)))

5-element Array{AbstractString,1}:
 "a"
 "b"
 "c"
 "d"
 "e"

In [137]:
[2, 2, 2]

3-element Array{Int64,1}:
 2
 2
 2

In [138]:
a = [[1, 2, 3] [4, 5, 6]]
b = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [139]:
a * b

LoadError: LoadError: DimensionMismatch("matrix A has dimensions (3,2), vector B has length 3")
while loading In[139], in expression starting on line 1

In [140]:
a .* b

3x2 Array{Int64,2}:
 1   4
 4  10
 9  18

In [141]:
repmat([1, 2], 3)

6-element Array{Int64,1}:
 1
 2
 1
 2
 1
 2

In [144]:
my_dictionary = Dict("A" => 200)
in(("A" => 200), my_dictionary)

true

In [145]:
function cbd(a)
    return a^3
end

cbd (generic function with 1 method)

In [146]:
cbd("a")

"aaa"

In [147]:
cbd([1, 2, 4])

LoadError: LoadError: MethodError: `*` has no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
  *{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(!Matched::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, ::Union{DenseArray{S,1},SubArray{S,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  *{TA,TB}(!Matched::Base.LinAlg.AbstractTriangular{TA,S<:AbstractArray{T,2}}, ::Union{DenseArray{TB,1},DenseArray{TB,2},SubArray{TB,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD},SubArray{TB,2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  ...
while loading In[147], in expression starting on line 1

In [148]:
cbd({1, 2})


Use "Any[a,b, ...]" instead.


LoadError: LoadError: MethodError: `*` has no method matching *(::Array{Any,1}, ::Array{Any,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
  *{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(!Matched::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, ::Union{DenseArray{S,1},SubArray{S,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  *{TA,TB}(!Matched::Base.LinAlg.AbstractTriangular{TA,S<:AbstractArray{T,2}}, ::Union{DenseArray{TB,1},DenseArray{TB,2},SubArray{TB,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD},SubArray{TB,2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  ...
while loading In[148], in expression starting on line 1

In [149]:
{1, 2}


Use "Any[a,b, ...]" instead.


2-element Array{Any,1}:
 1
 2

In [150]:
3 + 4

7

In [151]:
+(3, 5)

8

In [152]:
+(3 4)

LoadError: LoadError: syntax: missing separator in tuple
while loading In[152], in expression starting on line 1

In [153]:
(+ 3  4)

LoadError: LoadError: syntax: missing separator in tuple
while loading In[153], in expression starting on line 1

In [154]:
+(3, 4, 5, 6, 7, 7)

32

In [155]:
*(3, 4,5, 6, 7)

2520

In [156]:
/(3, 4, 6)

LoadError: LoadError: MethodError: `/` has no method matching /(::Int64, ::Int64, ::Int64)
Closest candidates are:
  /(::Integer, ::Integer)
  /{T<:Number}(::T<:Number, ::T<:Number)
  /(::Number, ::Number)
  ...
while loading In[156], in expression starting on line 1

In [157]:
f(x) = x^2

f (generic function with 1 method)

In [158]:
methods(f)

# 1 method for generic function "f":
f(x) at In[157]:1

In [159]:
f(3)

9

In [160]:
function mltpl(x, y)
    print("The first value is $x and the second values is $y.\n$x x $y is:")
    return x * y
end

mltpl (generic function with 1 method)

In [161]:
mltpl(3, 4)

The first value is 3 and the second values is 4.
3 x 4 is:

12

In [162]:
function mltpl(x, y)
    x + y
    x * y
end

mltpl (generic function with 1 method)

In [163]:
mltpl(3, 4)

12

In [165]:
function func(a, b, c = 100)
    print("We have the values $a, $b, and $c.")
end

func (generic function with 2 methods)

In [166]:
func(1, 2)

We have the values 1, 2, and 100.

In [167]:
func(1, 2, 4)

We have the values 1, 2, and 4.

In [169]:
function func2(a, b, c = 100 ; p = 100,  q = "red")
    println("The first ordered argument is $(a).")
    println("The second ordered argument is $(b).")
    println("The third ordered argument is optional.")
    println("If you see a value of 100 here, you either passed a value of 100 or omitted it: $(c).")
    println("Let's see what happened to the keyword p: $(p).")
    println("Let's see what happened to the keyword q: $(q).")
    println("Oh, yes, let's also return something useful, like multiplying $(a) and $(b), yielding: ")
    return a * b
end

func2 (generic function with 2 methods)

In [170]:
func2(10, 20)

The first ordered argument is 10.
The second ordered argument is 20.
The third ordered argument is optional.
If you see a value of 100 here, you either passed a value of 100 or omitted it: 100.
Let's see what happened to the keyword p: 100.
Let's see what happened to the keyword q: red.
Oh, yes, let's also return something useful, like multiplying 10 and 20, yielding: 


200

In [171]:
func2(10, 20, 30)

The first ordered argument is 10.
The second ordered argument is 20.
The third ordered argument is optional.
If you see a value of 100 here, you either passed a value of 100 or omitted it: 30.
Let's see what happened to the keyword p: 100.
Let's see what happened to the keyword q: red.
Oh, yes, let's also return something useful, like multiplying 10 and 20, yielding: 


200

In [172]:
func2(10, 20, 300 ; 30, "blue")

LoadError: LoadError: BoundsError
while loading In[172], in expression starting on line 1

In [173]:
func2(10, 20, p = pi)

The first ordered argument is 10.
The second ordered argument is 20.
The third ordered argument is optional.
If you see a value of 100 here, you either passed a value of 100 or omitted it: 100.
Let's see what happened to the keyword p: π = 3.1415926535897....
Let's see what happened to the keyword q: red.
Oh, yes, let's also return something useful, like multiplying 10 and 20, yielding: 


200

In [174]:
♠ = 100

100

In [175]:
♠

100

In [177]:
function func3(args...)
    print("I can tell you how many arguments you passed: $(length(args)).")
end

func3 (generic function with 1 method)

In [178]:
func3("a", "b", "c", "d")

I can tell you how many arguments you passed: 4.

In [179]:
function surgery(string_array)
    string_items = join(string_array, ", ", " and ")
    print("Today I performed the following operations: $string_items\!")
end

surgery (generic function with 1 method)

In [180]:
surgery(["colonic resection", "appendectomy"])

Today I performed the following operations: colonic resection and appendectomy!

In [181]:
surgery("appendectomy")

Today I performed the following operations: a, p, p, e, n, d, e, c, t, o, m and y!

In [182]:
function splat_surgery(stringsss...)
    string_items = join(stringsss, ", " , " and ")
    print("Today I performed the following operations: $string_items\!")
end

splat_surgery (generic function with 1 method)

In [183]:
splat_surgery("appendectomy")

Today I performed the following operations: appendectomy!

In [184]:
splat_surgery("appendectomy", "colonic resection", "omentopexy")

Today I performed the following operations: appendectomy, colonic resection and omentopexy!

In [185]:
function argues(a, b, s...)
    print("The argument values are: $a, $b, and $s")
end

argues (generic function with 1 method)

In [186]:
argues(3, 4, 5, 6, 7, 8, "julia")

The argument values are: 3, 4, and (5,6,7,8,"julia")

In [187]:
function fun_func(; a...)
    a
end

fun_func (generic function with 1 method)

In [188]:
fun_func(a = pi)

1-element Array{Any,1}:
 (:a,π = 3.1415926535897...)

In [189]:
fun_func(var1 = "Julia", var2 = "Language", val1 = 3)

3-element Array{Any,1}:
 (:var1,"Julia")   
 (:var2,"Language")
 (:val1,3)         